/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.lpoo.alisson.models.view;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import projeto.lpoo.alisson.dao.PersistenciaJPA;
import projeto.lpoo.alisson.models.Animal;


/**
 *
 * @author aliss
 */
public class TelaAnimais extends javax.swing.JFrame {
    
    PersistenciaJPA persistencia;

    /**
     * Creates new form TelaAnimais
     */
    public TelaAnimais() {
        initComponents();
        carregarAnimais();
    }

    private void carregarAnimais(){
        lstAnim.clearSelection();
        persistencia = new PersistenciaJPA();
        persistencia.conexaoAberta();
        List<Animal> ListaAnimal = persistencia.getAnimais();
        System.out.println("Lista " +ListaAnimal);
        DefaultListModel aniLista = new DefaultListModel<>();
        for(Animal a: ListaAnimal){
            aniLista.addElement(a);
        }
        lstAnim.setModel(aniLista);
        persistencia.fecharConexao();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstAnim = new javax.swing.JList<>();
        LblTitle = new javax.swing.JLabel();
        BttNewAnim = new javax.swing.JButton();
        bttRemover = new javax.swing.JButton();
        bttExit = new javax.swing.JButton();
        bttServicos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtLbl.setText("Animais:");

        jScrollPane1.setViewportView(lstAnim);

        LblTitle.setText("PetShop do Alisson");

        BttNewAnim.setText("Novo");
        BttNewAnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BttNewAnimActionPerformed(evt);
            }
        });

        bttRemover.setText("Remover");
        bttRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRemoverActionPerformed(evt);
            }
        });

        bttExit.setText("Sair");
        bttExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttExitActionPerformed(evt);
            }
        });

        bttServicos.setText("Adicionar Serviços");
        bttServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttServicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttServicos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BttNewAnim)
                                    .addComponent(bttRemover))))
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(bttExit)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BttNewAnim)
                        .addGap(18, 18, 18)
                        .addComponent(bttRemover)
                        .addGap(18, 18, 18)
                        .addComponent(bttServicos)))
                .addGap(47, 47, 47)
                .addComponent(bttExit)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BttNewAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BttNewAnimActionPerformed
       TelaNovoAnimal tela = new TelaNovoAnimal(this, true);
       
       tela.setVisible(true);
       
       carregarAnimais();
    }//GEN-LAST:event_BttNewAnimActionPerformed

    private void bttRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRemoverActionPerformed
        Animal animalSelecionado = lstAnim.getSelectedValue();
        if(animalSelecionado != null){
            int confirmacaoDel = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja remover "
                    + animalSelecionado.getNome());
            if (confirmacaoDel == JOptionPane.YES_OPTION){
                try{
                persistencia = new PersistenciaJPA();
                persistencia.conexaoAberta();
                persistencia.remover(animalSelecionado);
                persistencia.fecharConexao();
                carregarAnimais();
                }catch(Exception e){
                    System.out.println("Erro ao excluir modalidade: " + e.getMessage());
                }finally{
                    persistencia.fecharConexao();
                }
                
            }else{
                JOptionPane.showMessageDialog(rootPane,
                    "Nenhuma modalidade selecionada");
            }
        }
    }//GEN-LAST:event_bttRemoverActionPerformed

    private void bttExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttExitActionPerformed
        dispose();
    }//GEN-LAST:event_bttExitActionPerformed

    private void bttServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttServicosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAnimais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAnimais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BttNewAnim;
    private javax.swing.JLabel LblTitle;
    private javax.swing.JButton bttExit;
    private javax.swing.JButton bttRemover;
    private javax.swing.JButton bttServicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Animal> lstAnim;
    private javax.swing.JLabel txtLbl;
    // End of variables declaration//GEN-END:variables
}
